name: zarr-experiments
channels:
  - conda-forge
dependencies:
  - python=3.7
  - rasterio
  - numpy
  - scipy
  - pandas
  - xarray
  - matplotlib
  - dask
  - distributed
  - gcsfs
  - s3fs
  - scikit-image
  - scikit-learn
  - dask-ml
  - bokeh
  - pyviz/label/earthsim::holoviews
  - jupyter-server-proxy
  - pyviz/label/earthsim::panel
  - geoviews
  - hvplot
  - rasterio
  - geopandas
  - fiona
  - shapely
  - pyproj
  - datashader
  - netcdf4
  - zarr
  - numcodecs
  - python-blosc
  - lz4
  - nbserverproxy
  - jupyter
  - jupyterlab=0.35
  - eccodes
  - ipywidgets
  - ipyleaflet
  - cfgrib
  - graphviz
  - dask-kubernetes
  - pip:
    - git+https://github.com/xgcm/xgcm.git
    - git+https://github.com/pydata/xarray.git
    - git+https://github.com/sebastienlanglois/hydrotools.git


